export const PSU_POWER_RESERVE_PERCENT = 20;
export const OTHER_COMPONENTS_POWER_WATTS = 100;
export const BOTTLENECK_WARNING_THRESHOLD = 35;
export const BOTTLENECK_CRITICAL_THRESHOLD = 55;
export const COOLING_RESERVE_PERCENT = 20;
