import Link from 'next/link';
import { Button } from '@/src/components/ui/Button';
import { Card } from '@/src/components/ui/Card';

const features = [
  ['Проверка совместимости', 'Контроль сокетов, питания, габаритов и интерфейсов в реальном времени.'],
  ['Подбор по бюджету', 'Баланс производительности и стоимости под выбранный сценарий.'],
  ['Расчёт энергопотребления', 'Оценка нагрузки и рекомендуемая мощность блока питания.'],
  ['Сохранение и экспорт', 'Готовые сборки в JSON и PDF для отчётов и презентации.']
];

export default function HomePage() {return <section className="space-y-10"><Card className="grid gap-8 overflow-hidden p-8 sm:grid-cols-2 sm:p-10"><div><p className="mb-4 inline-flex rounded-full border border-blue-400/30 bg-blue-500/10 px-3 py-1 text-xs font-medium text-blue-200">Веб-конфигуратор игровых ПК</p><h1 className="max-w-3xl text-4xl font-bold tracking-tight text-white sm:text-5xl">Подберите совместимую игровую сборку без ошибок</h1><p className="mt-4 max-w-2xl text-base text-slate-300">Подбор комплектующих с проверкой совместимости, контролем бюджета и оценкой энергопотребления в одном интерфейсе.</p><div className="mt-7 flex flex-wrap gap-3"><Link href="/auto-build"><Button size="lg">Автоматический подбор</Button></Link><Link href="/manual-build"><Button variant="secondary" size="lg">Собрать вручную</Button></Link></div></div><div className="rounded-2xl border border-white/10 bg-[#111827] p-5"><p className="text-sm text-slate-400">Пример конфигурации</p><p className="mt-2 text-lg font-semibold text-white">QHD Ultra Gaming</p><div className="mt-4 space-y-2 text-sm text-slate-300"><p>Статус: <span className="text-emerald-400">Совместима</span></p><p>Стоимость: <span className="text-white">184 900 ₽</span></p><p>Энергопотребление: <span className="text-white">542 Вт</span></p><p>Рекомендованный БП: <span className="text-white">750 Вт</span></p></div></div></Card><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-4">{features.map(([title,text])=><Card key={title}><h3 className="text-base font-semibold text-white">{title}</h3><p className="mt-2 text-sm text-slate-400">{text}</p></Card>)}</div><Card><h2 className="text-2xl font-semibold text-white">Как это работает</h2><div className="mt-4 grid gap-4 md:grid-cols-3">{['Выберите параметры','Получите конфигурацию','Сохраните и экспортируйте'].map((s,i)=><div key={s} className="rounded-xl border border-white/10 bg-[#111827] p-4"><p className="text-xs text-slate-500">Шаг {i+1}</p><p className="mt-1 font-medium text-slate-100">{s}</p></div>)}</div></Card><Card className="text-center"><h3 className="text-2xl font-semibold text-white">Готовы начать сборку?</h3><p className="mt-2 text-slate-400">Выберите удобный режим: интеллектуальный автоподбор или ручной контроль каждого компонента.</p><div className="mt-4 flex justify-center gap-3"><Link href="/auto-build"><Button>Перейти к автоподбору</Button></Link><Link href="/manual-build"><Button variant="secondary">Открыть ручной конфигуратор</Button></Link></div></Card></section>; }
